package com.amdocs.nestedinterface;

/**
 * the internal code generated by the java compiler is as follows,
 * 
 * public static interface OuterInterface$InnerInterface {
 * 		
 * 		public abstract void msg();
 * }
 * 
 * An interface within another interface should have public access modifier!
 * 
 * @author Amit
 *
 */
public interface OuterInterface {

	public interface InnerInterface {
		void msg();
	}
	
}
