package com.amdocs.nestedinterface;

/**
 * the internal code generated by the java compiler is as follows,
 * 
 * public static interface OuterInterface$InnerInterface {
 * 		
 * 		public abstract void msg();
 * }
 * 
 * An interface within another interface should have public access modifier!
 * 
 * Why we use nested interfaces?
 * 
 * 	1. Nested interfaces help in grouping the logical interfaces in one place
 * 	2. It increases the encapsulation
 * 	3. Nested interfaces can lead to readable and maintainable code
 * 
 * @author Amit
 *
 */
public interface OuterInterface {

	public interface InnerInterface {
		void msg();
	}
	
}
